"""initial schema

Revision ID: 929f8dd7b099
Revises: 
Create Date: 2026-04-10 21:38:55.230188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929f8dd7b099'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_mapping_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False, comment='映射分类'),
    sa.Column('source_value', sa.String(length=64), nullable=False, comment='阿里云枚举值'),
    sa.Column('target_value', sa.String(length=64), nullable=True, comment='腾讯云枚举值'),
    sa.Column('is_compatible', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'source_value', name='uk_category_source')
    )
    with op.batch_alter_table('enum_mapping_rule', schema=None) as batch_op:
        batch_op.create_index('idx_emr_category', ['category'], unique=False)

    op.create_table('migration_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_no', sa.String(length=32), nullable=False, comment='任务编号'),
    sa.Column('task_name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('status', sa.Enum('draft', 'ready', 'running', 'paused', 'completed', 'failed', 'cancelled', name='task_status'), nullable=False, comment='任务状态'),
    sa.Column('current_step', sa.Enum('credential', 'select_source', 'mapping', 'plan', 'execute', 'report', name='wizard_step'), nullable=False, comment='当前向导步骤'),
    sa.Column('failure_mode', sa.Enum('pause', 'continue', name='failure_mode'), nullable=False, comment='失败处理模式'),
    sa.Column('source_cloud', sa.String(length=16), nullable=False),
    sa.Column('source_region', sa.String(length=32), nullable=False),
    sa.Column('target_cloud', sa.String(length=16), nullable=False),
    sa.Column('target_region', sa.String(length=32), nullable=False),
    sa.Column('target_mode', sa.Enum('existing', 'create_new', name='target_mode'), nullable=False, comment='目标实例模式'),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('incompatible_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    with op.batch_alter_table('migration_task', schema=None) as batch_op:
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_migration_task_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('execution_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_item_id', sa.BigInteger(), nullable=True),
    sa.Column('log_level', sa.Enum('info', 'warn', 'error', 'debug', name='log_level_enum'), nullable=False),
    sa.Column('log_type', sa.Enum('system', 'api_call', 'user_action', 'confirm', 'error', 'progress', name='log_type_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['migration_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_log', schema=None) as batch_op:
        batch_op.create_index('idx_log_task', ['task_id'], unique=False)
        batch_op.create_index('idx_log_task_time', ['task_id', 'logged_at'], unique=False)

    op.create_table('instance_mapping',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('source_instance_id', sa.String(length=64), nullable=False),
    sa.Column('source_instance_name', sa.String(length=128), nullable=False),
    sa.Column('source_vip', sa.String(length=64), nullable=False),
    sa.Column('source_network_type', sa.String(length=16), nullable=False),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('target_instance_id', sa.String(length=64), nullable=False),
    sa.Column('target_instance_name', sa.String(length=128), nullable=False),
    sa.Column('target_vip', sa.String(length=64), nullable=False),
    sa.Column('target_created_by_system', sa.Boolean(), nullable=False),
    sa.Column('mapping_type', sa.Enum('one_to_one', 'many_to_one', name='mapping_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['migration_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instance_mapping', schema=None) as batch_op:
        batch_op.create_index('idx_im_source', ['source_instance_id'], unique=False)
        batch_op.create_index('idx_im_target', ['target_instance_id'], unique=False)
        batch_op.create_index('idx_im_task_id', ['task_id'], unique=False)

    op.create_table('migration_report',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('incompatible_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.BigInteger(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['migration_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('mapping_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('listener', 'forwarding_rule', 'health_check', 'acl', 'session', 'timeout', 'bandwidth', name='source_type_enum'), nullable=False),
    sa.Column('source_ref_id', sa.BigInteger(), nullable=True),
    sa.Column('source_description', sa.String(length=256), nullable=False),
    sa.Column('mapping_status', sa.Enum('mapped', 'incompatible', 'partial', 'manual', name='mapping_status_enum'), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=False),
    sa.Column('target_config', sa.JSON(), nullable=True),
    sa.Column('diff_summary', sa.String(length=512), nullable=True),
    sa.Column('user_action', sa.Enum('accept', 'skip', 'modify', name='user_action_enum'), nullable=False),
    sa.Column('user_modified_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['instance_mapping.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['migration_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mapping_result', schema=None) as batch_op:
        batch_op.create_index('idx_mr_mapping_id', ['mapping_id'], unique=False)
        batch_op.create_index('idx_mr_status', ['mapping_status'], unique=False)
        batch_op.create_index('idx_mr_task_id', ['task_id'], unique=False)

    op.create_table('migration_plan_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('mapping_result_id', sa.BigInteger(), nullable=True),
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('create_instance', 'create_listener', 'create_rule', 'modify_listener', 'modify_rule', 'set_health_check', 'set_acl', 'set_timeout', 'set_session', 'set_bandwidth', name='operation_type_enum'), nullable=False),
    sa.Column('operation_desc', sa.String(length=256), nullable=False),
    sa.Column('target_instance_id', sa.String(length=64), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_detail', sa.JSON(), nullable=True),
    sa.Column('conflict_action', sa.Enum('overwrite', 'skip', 'create_new', name='conflict_action_enum'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'waiting_confirm', 'confirmed', 'running', 'success', 'failed', 'skipped', 'cancelled', name='plan_item_status_enum'), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['instance_mapping.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['migration_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_plan_item', schema=None) as batch_op:
        batch_op.create_index('idx_plan_status', ['status'], unique=False)
        batch_op.create_index('idx_plan_task', ['task_id'], unique=False)
        batch_op.create_index('idx_plan_task_seq', ['task_id', 'seq_no'], unique=False)

    op.create_table('report_detail',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_item_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.Enum('success', 'failed', 'skipped', 'incompatible', name='report_category_enum'), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('operation_desc', sa.String(length=256), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('target_config', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('incompatible_reason', sa.String(length=512), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['migration_report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_detail', schema=None) as batch_op:
        batch_op.create_index('idx_rd_category', ['category'], unique=False)
        batch_op.create_index('idx_rd_report', ['report_id'], unique=False)
        batch_op.create_index('idx_rd_task', ['task_id'], unique=False)

    op.create_table('source_clb_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('raw_config', sa.JSON(), nullable=False),
    sa.Column('listeners_config', sa.JSON(), nullable=True),
    sa.Column('health_check_config', sa.JSON(), nullable=True),
    sa.Column('forwarding_rules', sa.JSON(), nullable=True),
    sa.Column('advanced_params', sa.JSON(), nullable=True),
    sa.Column('acl_policies', sa.JSON(), nullable=True),
    sa.Column('bandwidth_config', sa.JSON(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['instance_mapping.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['migration_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_clb_snapshot', schema=None) as batch_op:
        batch_op.create_index('idx_snap_instance_id', ['instance_id'], unique=False)
        batch_op.create_index('idx_snap_mapping_id', ['mapping_id'], unique=False)
        batch_op.create_index('idx_snap_task_id', ['task_id'], unique=False)

    op.create_table('incompatible_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('mapping_result_id', sa.BigInteger(), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('source_value', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'info', name='severity_enum'), nullable=False),
    sa.Column('suggestion', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['mapping_result_id'], ['mapping_result.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['migration_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incompatible_item', schema=None) as batch_op:
        batch_op.create_index('idx_inc_mr', ['mapping_result_id'], unique=False)
        batch_op.create_index('idx_inc_task', ['task_id'], unique=False)

    op.create_table('source_acl_policy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('listener_id', sa.BigInteger(), nullable=True),
    sa.Column('acl_id', sa.String(length=64), nullable=False),
    sa.Column('acl_name', sa.String(length=128), nullable=False),
    sa.Column('acl_type', sa.String(length=16), nullable=False),
    sa.Column('acl_entries', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_clb_snapshot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_acl_policy', schema=None) as batch_op:
        batch_op.create_index('idx_acl_snapshot', ['snapshot_id'], unique=False)

    op.create_table('source_listener',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('listener_port', sa.Integer(), nullable=False),
    sa.Column('listener_protocol', sa.String(length=8), nullable=False),
    sa.Column('backend_port', sa.Integer(), nullable=True),
    sa.Column('scheduler', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('connection_timeout', sa.Integer(), nullable=True),
    sa.Column('idle_timeout', sa.Integer(), nullable=True),
    sa.Column('request_timeout', sa.Integer(), nullable=True),
    sa.Column('sticky_session', sa.Enum('on', 'off', name='sticky_enum'), nullable=False),
    sa.Column('sticky_session_type', sa.String(length=16), nullable=True),
    sa.Column('cookie_timeout', sa.Integer(), nullable=True),
    sa.Column('cookie', sa.String(length=128), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_clb_snapshot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_listener', schema=None) as batch_op:
        batch_op.create_index('idx_listener_port_proto', ['instance_id', 'listener_port', 'listener_protocol'], unique=False)
        batch_op.create_index('idx_listener_snapshot', ['snapshot_id'], unique=False)
        batch_op.create_index('idx_listener_task', ['task_id'], unique=False)

    op.create_table('source_forwarding_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('listener_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('url_path', sa.String(length=512), nullable=False),
    sa.Column('scheduler', sa.String(length=32), nullable=True),
    sa.Column('sticky_session', sa.Enum('on', 'off', name='rule_sticky_enum'), nullable=True),
    sa.Column('sticky_session_type', sa.String(length=16), nullable=True),
    sa.Column('cookie_timeout', sa.Integer(), nullable=True),
    sa.Column('health_check_enabled', sa.Enum('on', 'off', name='rule_hc_enum'), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['source_listener.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_forwarding_rule', schema=None) as batch_op:
        batch_op.create_index('idx_rule_listener', ['listener_id'], unique=False)
        batch_op.create_index('idx_rule_task', ['task_id'], unique=False)

    op.create_table('source_health_check',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('listener_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('health_check_enabled', sa.Enum('on', 'off', name='hc_enabled_enum'), nullable=False),
    sa.Column('check_type', sa.String(length=8), nullable=True),
    sa.Column('check_port', sa.Integer(), nullable=True),
    sa.Column('check_path', sa.String(length=256), nullable=True),
    sa.Column('check_domain', sa.String(length=256), nullable=True),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('check_timeout', sa.Integer(), nullable=True),
    sa.Column('healthy_threshold', sa.Integer(), nullable=True),
    sa.Column('unhealthy_threshold', sa.Integer(), nullable=True),
    sa.Column('http_code', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['source_listener.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_health_check', schema=None) as batch_op:
        batch_op.create_index('idx_hc_listener', ['listener_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_health_check', schema=None) as batch_op:
        batch_op.drop_index('idx_hc_listener')

    op.drop_table('source_health_check')
    with op.batch_alter_table('source_forwarding_rule', schema=None) as batch_op:
        batch_op.drop_index('idx_rule_task')
        batch_op.drop_index('idx_rule_listener')

    op.drop_table('source_forwarding_rule')
    with op.batch_alter_table('source_listener', schema=None) as batch_op:
        batch_op.drop_index('idx_listener_task')
        batch_op.drop_index('idx_listener_snapshot')
        batch_op.drop_index('idx_listener_port_proto')

    op.drop_table('source_listener')
    with op.batch_alter_table('source_acl_policy', schema=None) as batch_op:
        batch_op.drop_index('idx_acl_snapshot')

    op.drop_table('source_acl_policy')
    with op.batch_alter_table('incompatible_item', schema=None) as batch_op:
        batch_op.drop_index('idx_inc_task')
        batch_op.drop_index('idx_inc_mr')

    op.drop_table('incompatible_item')
    with op.batch_alter_table('source_clb_snapshot', schema=None) as batch_op:
        batch_op.drop_index('idx_snap_task_id')
        batch_op.drop_index('idx_snap_mapping_id')
        batch_op.drop_index('idx_snap_instance_id')

    op.drop_table('source_clb_snapshot')
    with op.batch_alter_table('report_detail', schema=None) as batch_op:
        batch_op.drop_index('idx_rd_task')
        batch_op.drop_index('idx_rd_report')
        batch_op.drop_index('idx_rd_category')

    op.drop_table('report_detail')
    with op.batch_alter_table('migration_plan_item', schema=None) as batch_op:
        batch_op.drop_index('idx_plan_task_seq')
        batch_op.drop_index('idx_plan_task')
        batch_op.drop_index('idx_plan_status')

    op.drop_table('migration_plan_item')
    with op.batch_alter_table('mapping_result', schema=None) as batch_op:
        batch_op.drop_index('idx_mr_task_id')
        batch_op.drop_index('idx_mr_status')
        batch_op.drop_index('idx_mr_mapping_id')

    op.drop_table('mapping_result')
    op.drop_table('migration_report')
    with op.batch_alter_table('instance_mapping', schema=None) as batch_op:
        batch_op.drop_index('idx_im_task_id')
        batch_op.drop_index('idx_im_target')
        batch_op.drop_index('idx_im_source')

    op.drop_table('instance_mapping')
    with op.batch_alter_table('execution_log', schema=None) as batch_op:
        batch_op.drop_index('idx_log_task_time')
        batch_op.drop_index('idx_log_task')

    op.drop_table('execution_log')
    with op.batch_alter_table('migration_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_task_is_deleted'))
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_created_at')

    op.drop_table('migration_task')
    with op.batch_alter_table('enum_mapping_rule', schema=None) as batch_op:
        batch_op.drop_index('idx_emr_category')

    op.drop_table('enum_mapping_rule')
    # ### end Alembic commands ###
